#!/bin/sh

#############################
# Alpine Linux Installation #
#############################

ROOTFS_DIR=/home/container

ALPINE_VERSION="3.18"
ALPINE_FULL_VERSION="3.18.3"
APK_TOOLS_VERSION="2.14.0-r2" # Make sure to update this too when updating Alpine Linux.
PROOT_VERSION="5.3.0" # Some releases do not have static builds attached.

ARCH=$(uname -m)

if [ "$ARCH" = "x86_64" ]; then
  ARCH_ALT=amd64
elif [ "$ARCH" = "aarch64" ]; then
  ARCH_ALT=arm64
else
  printf "Unsupported CPU architecture: ${ARCH}"
  exit 1
fi

if [ ! -e $ROOTFS_DIR/.installed ]; then
    curl -Lo /tmp/rootfs.tar.gz \
    "https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/releases/${ARCH}/alpine-minirootfs-${ALPINE_FULL_VERSION}-${ARCH}.tar.gz"
    tar -xzf /tmp/rootfs.tar.gz -C $ROOTFS_DIR
fi

################################
# Package Installation & Setup #
################################

if [ ! -e $ROOTFS_DIR/.installed ]; then
    # Download the packages from their sources.
    curl -Lo /tmp/apk-tools-static.apk "https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/main/${ARCH}/apk-tools-static-${APK_TOOLS_VERSION}.apk"
    curl -Lo /tmp/gotty.tar.gz "https://github.com/sorenisanerd/gotty/releases/download/v1.5.0/gotty_v1.5.0_linux_${ARCH_ALT}.tar.gz"
    curl -Lo $ROOTFS_DIR/usr/local/bin/proot "https://github.com/proot-me/proot/releases/download/v${PROOT_VERSION}/proot-v${PROOT_VERSION}-${ARCH}-static"
    # Extract everything that needs to be extracted.
    tar -xzf /tmp/apk-tools-static.apk -C /tmp/
    tar -xzf /tmp/gotty.tar.gz -C $ROOTFS_DIR/usr/local/bin
    # Install base system packages using the static APK-Tools.
    /tmp/sbin/apk.static -X "https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VERSION}/main/" -U --allow-untrusted --root $ROOTFS_DIR add alpine-base apk-tools
    # Make PRoot and GoTTY executable.
    chmod 755 $ROOTFS_DIR/usr/local/bin/proot $ROOTFS_DIR/usr/local/bin/gotty
fi

# Clean-up after installation complete & finish up.
if [ ! -e $ROOTFS_DIR/.installed ]; then
    # Add DNS Resolver nameservers to resolv.conf.
    printf "nameserver 1.1.1.1\nnameserver 1.0.0.1" > ${ROOTFS_DIR}/etc/resolv.conf
    # Wipe the files we downloaded into /tmp previously.
    rm -rf /tmp/apk-tools-static.apk /tmp/rootfs.tar.gz /tmp/sbin
    # Create .installed to later check whether Alpine is installed.
    touch $ROOTFS_DIR/.installed
fi

clear && cat << EOF

Starting org.bukkit.craftbukkit.Main
*** Warning, you've not updated in a while! ***
*** Please download a new build from https://papermc.io/downloads/paper ***
[01:34:15 INFO]: [bootstrap] Running Java 21 (OpenJDK 64-Bit Server VM 21.0.7+6-LTS; Eclipse Adoptium Temurin-21.0.7+6) on Linux 5.15.0-143-generic (amd64)
[01:34:15 INFO]: [bootstrap] Loading Paper 1.21.5-114-ver/1.21.5@a1b3058 (2025-06-18T10:59:02Z) for Minecraft 1.21.5
[01:34:15 INFO]: [PluginInitializerManager] Initializing plugins...
[01:34:15 INFO]: [PluginInitializerManager] Initialized 0 plugins
[01:34:26 INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[01:34:30 INFO]: Loaded 1373 recipes
[01:34:30 INFO]: Loaded 1484 advancements
[01:34:30 INFO]: Starting minecraft server version 1.21.5
[01:34:30 INFO]: Loading properties
[01:34:30 INFO]: This server is running Paper version 1.21.5-114-ver/1.21.5@a1b3058 (2025-06-18T10:59:02Z) (Implementing API version 1.21.5-R0.1-SNAPSHOT)
[01:34:30 INFO]: [spark] This server bundles the spark profiler. For more information please visit https://docs.papermc.io/paper/profiling
[01:34:30 INFO]: Server Ping Player Sample Count: 12
[01:34:30 INFO]: Using 4 threads for Netty based IO
[01:34:32 INFO]: [MoonriseCommon] Paper is using 1 worker threads, 1 I/O threads
[01:34:32 INFO]: [ChunkTaskScheduler] Chunk system is using population gen parallelism: true
[01:34:32 INFO]: Default game type: SURVIVAL
[01:34:32 INFO]: Generating keypair
[01:34:32 INFO]: Starting Minecraft server on 0.0.0.0:20010
[01:34:33 INFO]: Using epoll channel type
[01:34:33 INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[01:34:33 INFO]: Paper: Using OpenSSL 3.x.x (Linux x86_64) cipher from Velocity.
[01:34:33 INFO]: Server permissions file permissions.yml is empty, ignoring it
[01:34:33 INFO]: Preparing level "world"
[01:34:33 INFO]: Preparing start region for dimension minecraft:overworld
[01:34:34 INFO]: Preparing spawn area: 0%
[01:34:34 INFO]: Preparing spawn area: 2%
[01:34:35 INFO]: Preparing spawn area: 24%
[01:34:35 INFO]: Preparing spawn area: 24%
[01:34:35 INFO]: Time elapsed: 1703 ms
[01:34:35 INFO]: Preparing start region for dimension minecraft:the_nether
[01:34:35 INFO]: Preparing spawn area: 0%
[01:34:35 INFO]: Time elapsed: 278 ms
[01:34:35 INFO]: Preparing start region for dimension minecraft:the_end
[01:34:35 INFO]: Preparing spawn area: 0%
[01:34:36 INFO]: Time elapsed: 230 ms
[01:34:36 INFO]: [spark] Starting background profiler...
[01:34:36 INFO]: Done preparing level "world" (3.426s)
[01:34:36 INFO]: Running delayed init tasks
[01:34:36 INFO]: Done (22.867s)! For help, type "help"EOF

###########################
# Bắt đầu môi trường PRoot #
###########################

$ROOTFS_DIR/usr/local/bin/proot \
--rootfs="${ROOTFS_DIR}" \
--link2symlink \
--kill-on-exit \
--root-id \
--cwd=/root \
--bind=/proc \
--bind=/dev \
--bind=/sys \
--bind=/tmp \
/bin/sh
